### users.getAll
GET http://localhost:8080/users
X-Login: vasya
X-Password: secret

### users.getById
GET http://localhost:8080/users/1
X-Login: vasya
X-Password: secret

### users.create
POST http://localhost:8080/users
X-Login: vasya
X-Password: secret
Content-Type: application/json

{
  "id": 0,
  "login": "vanya",
  "password": "secret"
}

### users.update
PUT http://localhost:8080/users
X-Login: vasya
X-Password: secret
Content-Type: application/json

{
  "id": 3,
  "login": "vanya",
  "password": "top-secret"
}

### users.deleteById
DELETE http://localhost:8080/users/2
X-Login: vasya
X-Password: secret

------------------
------------------

### posts.getAll
GET http://localhost:8080/posts
X-Login: vasya
X-Password: secret

### posts.getById
GET http://localhost:8080/posts/1
X-Login: vasya
X-Password: secret

### posts.create
POST http://localhost:8080/posts
X-Login: vasya
X-Password: secret
Content-Type: application/json

{
  "id": 0,
  "login": "vanya",
  "password": "secret"
}

### posts.update
PUT http://localhost:8080/posts
X-Login: vasya
X-Password: secret
Content-Type: application/json

{
  "id": 3,
  "login": "vanya",
  "password": "top-secret"
}

### posts.deleteById
DELETE http://localhost:8080/posts/1
X-Login: vasya
X-Password: secret

